language: ruby
dist: xenial
cache: bundler

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2

matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_41.gemfile

gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile

script:
  - NO_RAILS=1 bundle exec rspec
  - bundle exec rspec
